### ISSUE TITLE
Question: how can I capture error parameters with `revertedWith`?

### ISSUE THREAD

**Issue by TravelingTechGuy** [TrueFiEng/Waffle#631] opened 2022-03-03 17:54 UTC
I have custom errors in my contract, that return useful info, such as:

```solidity
error MaxSupplyReached(uint16 left);
```

I have test code that expects the revert:

```javascript
await expect(token.connect(user3).mint(10, {value: tokenPrice(10)}))
        .to.be.revertedWith('MaxSupplyReached');
```

I want to test that the value of `left` is 9. I tried using `.withArgs` but apparently that does not work with `revertedWith`.

How can i capture error parameters in Waffle?

**Comment by colinsteidtmann** [comment] 2022-03-15 23:37
I have the same issue

**Comment by paulrberg** [comment] 2022-03-30 06:36
Duplicate of https://github.com/TrueFiEng/Waffle/issues/511.

**Comment by yivlad** [comment] 2022-05-06 14:13
Please refer to https://github.com/TrueFiEng/Waffle/blob/1e598c58f5454235e4b1eaaa2e104f20dc3977eb/waffle-hardhat/test/reverted.test.ts#L27-L34
Note that this works only with hardhat - that is `@ethereum-waffle/provider` doesn't support custom errors for now.

**Closed by yivlad** 2022-05-06 14:13 UTC
