### ISSUE TITLE
chai matcher `closeTo` 

### ISSUE THREAD

**Issue by SvenMeyer** [TrueFiEng/Waffle#561] opened 2021-09-01 08:47 UTC
I was trying to use `closeTo` but ran into issues as soon as delta had more than 15 digits.

```
const delta = ethers.utils.parseUnits("0.01", rewardsToken_decimals);
expect(rewardBalance).closeTo(expectedReward, delta);
```

Problem:

1) When dealing with `BigNumber` `delta` can become bigger than 15 digits , which leads to 

`Error: overflow (fault="overflow", operation="toNumber", value="10000000000000000", code=NUMERIC_FAULT, version=bignumber/5.4.1)`

2) delta can not be a `BigNumber`

**Comment by paulrberg** [comment] 2021-09-02 12:05
Duplicate of #512.

**Closed** 2022-05-06 13:56 UTC
