### ISSUE TITLE
Mock Contract not working with `calledOnContract`

### ISSUE THREAD

**Issue by Remscar** [TrueFiEng/Waffle#468] opened 2021-03-16 00:08 UTC
Hello,

I'm having difficulties with using the Mock Contract with the `calledOnContract` and `calledOnContractWith` matchers.

For reference I am using Ethereum Waffle with Hardhat.

Here is a sample of the used code:
```js

// setup
import * as registrar from "../artifacts/contracts/Registrar.sol/Registrar.json";

chai.use(solidity);
const { expect } = chai;

// making the mock
registrarMock = await deployMockContract(creator, registrar.abi);

// inside of a test
await registrarMock.mock.registerDomain.returns(returnedId);

// <--- call registerDomain from another contract --->

// check to see if function was called
expect("registerDomain").to.be.calledOnContract(registrarMock);
```

`calledOnContract` throws an exception: ` TypeError: argument must be a contract`

```
at Object.ensure (node_modules\@ethereum-waffle\chai\dist\cjs\matchers\calledOnContract\utils.js:6:15)
      at Object.validateContract (node_modules\@ethereum-waffle\chai\dist\cjs\matchers\calledOnContract\calledOnContractValidators.js:8:13)
      at Proxy.<anonymous> (node_modules\@ethereum-waffle\chai\dist\cjs\matchers\calledOnContract\calledOnContract.js:8:38)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at Context.<anonymous> (test\basiccontroller.spec.ts:66:44)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Happens with both `calledOnContract` and `calledOnContractWith` methods.

Relevant Versions:
```js
{
  "@nomiclabs/hardhat-waffle": "^2.0.1",
  "ethereum-waffle": "^3.3.0",
  "chai": "^4.3.3",
  "ethers": "^5.0.31"
}
```

**Comment by wachulski** [comment] 2021-03-25 12:57
Duplicate of #469

**Comment by rzadp** [comment] 2022-07-29 11:43
Closing as a duplicate. See https://github.com/TrueFiEng/Waffle/issues/469#issuecomment-1199181049

**Closed by rzadp** 2022-07-29 11:43 UTC
