### ISSUE TITLE
compare doesn't work when using structs

### ISSUE THREAD

**Issue by novaknole** [TrueFiEng/Waffle#454] opened 2021-03-01 19:27 UTC
My contract looks like this.

```js

struct test{
    uint256 num1;
    uint256 num2;
    Action[] actions;
}


struct Action {
    address to;
    uint256 value;
    bytes data;
}


event EventExample(test data);

function myFunction(test memory data) public {

   emit EventExample(data);

}

```

Then I want to test this, so I do the following:

```js

const data = {
    num1: 20,
    num2: 30,
    actions: [
      {
        to: 0x0000000000000000000000000000000000000000,
        value: 1000,
        data: 0x00
      }
    ],
}
await expect(contract.myFunction(data))
        .to.emit(contract, 'EventExample')
      .withArgs([
            data.num1,
            data.num2,
             [
                   [
                            data.to,
                            data.value, 
                            data.data
                   ]
             ]
      ])
```

It turns out that this results in an error.

> AssertionError: expected [ Array(1) ] to equal [ Array(1)]

Let's now forget about the `num1, num2` because they are not important and focus on `Actions`.

After some debugging, I figured out that after decoding the event that gets thrown, we get the following:

```js

//Actual Args for `Actions`
[
      '0x0000000000000000000000000000000000000000',
      [BigNumber],
      '0x00',
      to: '0x0000000000000000000000000000000000000000',
      value: [BigNumber],
      data: '0x00'
    ]

// Expected Args for `Actions`

[
 '0x0000000000000000000000000000000000000000',
      [BigNumber],
      '0x00',
]
```

Why does Actual Args contain duplicate ? and more importantly, it contains `to, value,data` and also without `to,value,data `, but they are the same

So the test fails.  To have the possibility for checking `deep include` or things that mocha supports might have solved it, but I can't do anything with `withArgs` at all. What would you suggest ?

**Comment by wchargin** [comment] 2021-05-01 05:51
Duplicate of #245?

**Comment by rzadp** [comment] 2022-08-01 08:45
Structs in the arguments are now handled in Waffle 4.
Feel free to open new issues if you encounter any problems with it in Waffle 4.

**Closed by rzadp** 2022-08-01 08:45 UTC
